// src/components/navbar/index.jsx
import { MdDarkMode, MdLightMode, MdMenu } from 'react-icons/md'

export function Navbar() {
  return (
    <div className="navbar">
      <button id="menu-btn">
        <MdMenu />
      </button>

      <div className="dark-mode">
        <MdLightMode className="active" />
        <MdDarkMode />
      </div>

      <div className="profile">
        <div className="info">
          <p>
            Hey, <b>Indra</b>
          </p>
          <small className="text-muted">Admin</small>
        </div>
        
        <div className="profile-photo">
          <img src="images/profile-1.jpg" />
        </div>
      </div>
    </div>
  )
}

// vue/src/components/Navbar.vue
<template>
  <div class="nav">
    <button id="menu-btn">
      <v-icon name="md-menu" />
    </button>

    <div class="dark-mode">
      <v-icon name="md-lightmode" class="active" />
      <v-icon name="md-darkmode" />
    </div>

    <div class="profile">
      <div class="info">
        <p>Hey, <b>Indra</b></p>
        <small class="text-muted">Admin</small>
      </div>
      <div class="profile-photo">
        <img src="images/profile-1.jpg" />
      </div>
    </div>
  </div>
</template>
