// src/components/new-user/index.jsx
import { User } from './user'

export function NewUser() {
  return (
    <div className="new-users">
      <h2>New Users</h2>
      <div className="user-list">
        {users.map((user, i) => <User key={i} {...user} />)}

        <User image="images/plus.png" name="More" caption="New User" />
      </div>
    </div>
  )
}

const users = [
  { image: 'images/profile-2.jpg', name: 'Jack', caption: '54 Min Ago' },
  { image: 'images/profile-3.jpg', name: 'Amir', caption: '3 Hours Ago' },
  { image: 'images/profile-4.jpg', name: 'Ember', caption: '6 Hours Ago' },
]

// vue/src/components/NewUser.vue
<script setup>
import NewUserCard from './NewUserCard.vue'

const users = [
  { image: 'images/profile-2.jpg', name: 'Jack', caption: '54 Min Ago' },
  { image: 'images/profile-3.jpg', name: 'Amir', caption: '3 Hours Ago' },
  { image: 'images/profile-4.jpg', name: 'Ember', caption: '6 Hours Ago' },
]
</script>

<template>
  <div class="new-users">
    <h2>New Users</h2>

    <div class="user-list">
      <NewUserCard
        v-for="(user, i) in users"
        :key="i"
        :name="user.name"
        :image="user.image"
        :caption="user.caption"
      />

      <NewUserCard image="images/plus.png" name="More" caption="New User" />
    </div>
  </div>
</template>
