// src/components/reminders/index.jsx
import { Notification } from './notification'

export function Reminders() {
  return (
    <div className="reminders">
      <div className="header">
        <h2>Reminders</h2>
        <span className="material-icons-sharp">notifications_none</span>
      </div>

      <Notification title="Workshop" time="08:00 AM - 12:00 PM" />
      <Notification title="Workshop" time="08:00 AM - 12:00 PM" deactive />
      <Notification addReminder />
    </div>
  )
}

// vue/src/components/Reminders.vue
<script setup>
import Notification from './Notification.vue'
</script>

<template>
  <div class="reminders">
    <div class="header">
      <h2>Reminders</h2>
      <v-icon name="md-notificationsnone" />
    </div>

    <Notification title="Workshop" time="08:00 AM - 12:00 PM" />
    <Notification title="Workshop" time="08:00 AM - 12:00 PM" deactive />
    <Notification add-reminder />
  </div>
</template>
