// vue/src/components/Notification.vue
<script setup>
defineProps({
  deactive: Boolean,
  addReminder: Boolean,
  title: String,
  time: String,
})
</script>

<template>
  <div class="notification" :class="{ deactive, 'add-reminder': addReminder }">
    <template v-if="!addReminder">
      <div class="icon">
        <v-icon :name="deactive ? 'md-edit' : 'md-volumeup'" />
      </div>

      <div class="content">
        <div class="info">
          <h3>{{ title }}</h3>
          <small class="text-muted">{{ time }}</small>
        </div>

        <MdMoreVert />
      </div>
    </template>

    <div v-else>
      <v-icon name="md-add" />
      <h3>Add Reminder</h3>
    </div>
  </div>
</template>

// src/components/reminders/notification.jsx
import { MdAdd, MdEdit, MdMoreVert, MdVolumeUp } from 'react-icons/md'

/**
 * @param {Object} props
 * @param {boolean} [props.deactive]
 * @param {boolean} [props.addReminder]
 * @param {string} props.title
 * @param {string} [props.time]
 */
export function Notification({ deactive, addReminder, title, time }) {
  return (
    <div
      className={`notification${
        deactive ? ' deactive' : addReminder ? ' add-reminder' : ''
      }`}
    >
      {!addReminder ? (
        <>
          <div className="icon">{deactive ? <MdEdit /> : <MdVolumeUp />}</div>

          <div className="content">
            <div className="info">
              <h3>{title}</h3>
              <small className="text_muted">{time}</small>
            </div>

            <MdMoreVert />
          </div>
        </>
      ) : (
        <div>
          <MdAdd />
          <h3>Add Reminder</h3>
        </div>
      )}
    </div>
  )
}
