// vue/src/components/SidebarToggle.vue
<script setup>
import logo from '@/assets/vue.svg'
</script>

<template>
  <div class="toggle">
    <section class="logo">
      <img :src="logo" alt="" />
      <h2>Vue<span class="primary">JS</span></h2>
    </section>

    <button class="close">
      <v-icon name="md-close" />
    </button>
  </div>
</template>

// src/components/sidebar-toggle.jsx
import logo from '@/assets/react.svg'
import { MdClose } from 'react-icons/md'

export function SidebarToggle() {
  return (
    <div className="toggle">
      <section className="logo">
        <img src={logo} alt="" />
        <h2>
          Freq<span className="danger">Seeker</span>
        </h2>
      </section>

      <button className="close" id="close-btn">
        <MdClose />
      </button>
    </div>
  )
}
