// vue/src/components/Sidebar.vue
<script setup>
import SidebarLink from './SidebarLink.vue'
import SidebarToggle from './SidebarToggle.vue'
</script>

<template>
  <aside>
    <SidebarToggle />

    <section class="sidebar">
      <SidebarLink title="Dashboard" icon="dashboard" />
      <SidebarLink title="Users" icon="person-outlined" />
      <SidebarLink title="History" icon="receiptlong" />
      <SidebarLink title="Analytics" icon="insights" />
      <SidebarLink title="Tickets" icon="mailoutline">
        <span class="message-count">69</span>
      </SidebarLink>
      <SidebarLink title="Sale List" icon="inventory" />
      <SidebarLink title="Reports" icon="reportgmailerrorred" />
      <SidebarLink title="Settings" icon="settings" />
      <SidebarLink title="New Login" icon="add" />
      <SidebarLink title="Logout" icon="logout" />
    </section>
  </aside>
</template>

// src/components/sidebar/index.jsx
import { SidebarLink } from './link'
import { SidebarToggle } from './toggle'
import * as Icon from 'react-icons/md'

export function Sidebar() {
  return (
    <aside>
      <SidebarToggle />

      <section className="sidebar">
        <SidebarLink title="Dashboard" icon={Icon.MdDashboard} />
        <SidebarLink title="Users" icon={Icon.MdPersonOutline} />
        <SidebarLink title="History" icon={Icon.MdReceiptLong} />
        <SidebarLink title="Analytics" icon={Icon.MdInsights} active />

        <SidebarLink title="Tickets" icon={Icon.MdMailOutline}>
          <span className="message-count">69</span>
        </SidebarLink>

        <SidebarLink title="Sale List" icon={Icon.MdInventory} />
        <SidebarLink title="Reports" icon={Icon.MdReportGmailerrorred} />
        <SidebarLink title="Settings" icon={Icon.MdSettings} />
        <SidebarLink title="New Login" icon={Icon.MdAdd} />
        <SidebarLink title="Logout" icon={Icon.MdLogout} />
      </section>
    </aside>
  )
}
