// vue/src/App.vue
<script setup>
import Sidebar from '@/components/Sidebar.vue'
import Analytics from './components/Analytics.vue'
import NewUser from './components/NewUser.vue'
import RecentOrders from './components/RecentOrders.vue'
import Navbar from './components/Navbar.vue'
import UserProfile from './components/UserProfile.vue'
</script>

<template>
  <div class="container">
    <Sidebar />

    <main>
      <Analytics />
      <NewUser />
      <RecentOrders />
    </main>

    <div class="right-section">
      <Navbar />
      <UserProfile />
    </div>
  </div>
</template>

<style scoped>
.container {
  display: grid;
  width: 96%;
  margin: 0 auto;
  gap: 1.8rem;
  grid-template-columns: 12rem auto 23rem;
}

main {
  margin-top: 1.4rem;
}

.right-section {
  margin-top: 1.4rem;
}
</style>

// src/app.jsx
import { Sidebar } from '@/components/sidebar'
import { Analytics } from '@/components/analytics'
import { NewUser } from '@/components/new-user'
import { RecentOrders } from '@/components/recent-orders'
import { Navbar } from '@/components/navbar'
import { UserProfile } from '@/components/user-profile'

export function App() {
  return (
    <div className="container">
      <Sidebar />

      <main>
        <Analytics />
        <NewUser />
        <RecentOrders />
      </main>

      <div className="right-section">
        <Navbar />
        <UserProfile />
      </div>
    </div>
  )
}
